Add Crud Status
GabrielNogueiraBR/InviteU pull request #13
Opened 2021-04-17 14:34 UTC by GabrielNogueiraBR

Foi realizada a criação dos endpoints responsáveis por manipular a entidade Status dentro de nosso projeto.

2021-04-17 14:52 UTC, VitorGois requested changes

2021-04-17 14:52 UTC, VitorGois commented on src/main/java/br/application/inviteu/dto/StatusInsertDTO.java
> +public class StatusInsertDTO {
No DTO como já é filtrado todos os itens que serão nesse caso inseridos no momento de sua criação, podemos reduzir ainda mais o código com o Lombok, ao invés de colocar todas essas anotações que você colocou, apenas coloque @Data que dentro dela há todas as outras.
AÍ pode ser mais vantajoso usar ela em DTO.

2021-04-17 14:52 UTC, VitorGois commented on src/main/java/br/application/inviteu/entities/Status.java
> +    public Status (String description){
Esse construtor aqui é para não ter o id? Com o @AllArgsConstructor  ele não exclui o Id do construtor?

2021-04-17 22:58 UTC, ryanraul commented on src/main/java/br/application/inviteu/entities/Status.java
> +    public Status (String description){
Não remove, vai o Id junto tb nos parâmetros.

2021-04-17 23:03 UTC, GabrielNogueiraBR commented on src/main/java/br/application/inviteu/entities/Status.java
> +    public Status (String description){
Exatamente como o Raul comentou, tive que personalizar esse construtor para ele ser chamado em outro trecho de código passando a String de description.

2021-04-17 23:52 UTC, ryanraul approved these changes

2021-04-17 23:59 UTC, VitorGois commented on src/main/java/br/application/inviteu/entities/Status.java
> +    public Status (String description){
Ah legal, foi bom ter falado, não consegui achar sobre. Eu vi que no HashCodeAndEquals há um parâmetro excludes, não sei se funciona em constructor, vou testar.

2021-04-18 00:20 UTC, VitorGois approved these changes

2021-04-18 00:20 UTC, merged